### ISSUE TITLE
Fancy updating the LSIO image?

### ISSUE THREAD

**Issue by ironicbadger** [magicdude4eva/docker-smokeping#1]
Hi, 

Saw your comment on Docker hub - we'd love you to come contribute at LSIO to our smokeping container (and others) if you're amenable. I'm the original author but haven't touched it in ages, it could definitely use some love. 

Nice work on the fixes here.

**Comment by magicdude4eva** [comment]
Thanks @IronicBadger - my current work commitments also did not give me enough time to focus on it. I am horrible with Docker and used this to learn about it. I have subsequently moved on to LibreNMS to monitor my devices.
